AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS SageMaker Endpoint'
Parameters:
  BucketName:
    Description: Name of data bucket
    MaxLength: '64'
    MinLength: '1'
    Type: String
  CommitID:
    Description: ID of the current commit
    MaxLength: '64'
    MinLength: '1'
    Type: String
  Environment:
    Description: Current environment we are working in
    MaxLength: '64'
    MinLength: '1'
    Type: String
  ParentStackName:
    Description: Name of pipeline stack
    MaxLength: '64'
    MinLength: '1'
    Type: String
  JobName:
    Description: Name of data bucket
    MaxLength: '64'
    MinLength: '1'
    Type: String
  SageMakerRole:
    Description: Name of SageMaker role
    MaxLength: '64'
    MinLength: '1'
    Type: String
  SageMakerImage:
    Description: Name of SageMaker training image
    MaxLength: '256'
    MinLength: '1'
    Type: String
  SageMakerInstanceType:
    Default: ml.c5.2xlarge
    Description: Type of Instance for SageMaker inference
    MaxLength: '64'
    MinLength: '1'
    Type: String
  Timestamp:
    Description: Resource timestamp to prevent naming conflicts
    MaxLength: '64'
    MinLength: '1'
    Type: String
Resources:
  Model:
    Type: "AWS::SageMaker::Model"
    DeletionPolicy: Delete
    Properties:
      ModelName: !Sub ${Environment}-${JobName}
      ExecutionRoleArn: !Sub ${SageMakerRole}
      PrimaryContainer:
        ModelDataUrl: !Sub s3://${BucketName}/${JobName}/output/model.tar.gz
        Image: !Sub ${SageMakerImage}
  Endpoint:
    Type: "AWS::SageMaker::Endpoint"
    DependsOn: EndpointConfig
    DeletionPolicy: Delete
    Properties:
      EndpointName: !Sub ${Environment}-${ParentStackName}
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName
  EndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    DependsOn: Model
    DeletionPolicy: Delete
    Properties:
        EndpointConfigName: !Sub ${Environment}-${JobName}
        ProductionVariants:
        - ModelName: !GetAtt Model.ModelName
          VariantName: AllTraffic
          InitialInstanceCount: 1
          InstanceType: !Sub ${SageMakerInstanceType}
          InitialVariantWeight: 1
